[package]
name = "bevy_experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
binreader = "0.2.1"
byteorder = "1.4.3"
