version: '2'

services:
  finagle-http:
    image: finagle-http
    environment:
      JAVA_OPTS: "-Dzipkin.initialSampleRate=1.0 -Dzipkin.http.host=jaeger-collector:9411"
    ports:
      - "8081:8080"
    depends_on:
      - jaeger-collector
      - finagle-thrift

  finagle-thrift:
    image: finagle-thrift
    environment:
      JAVA_OPTS: "-Dzipkin.initialSampleRate=1.0 -Dzipkin.http.host=jaeger-collector:9411"
    ports:
      - "8080"

  spring-boot:
    image: spring-boot
    environment:
      JAEGER_SERVICE_NAME: spring-boot
      JAEGER_AGENT_HOST: jaeger-agent
      JAEGER_AGENT_PORT: 5775
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_REPORTER_LOG_SPANS: "true"
    ports:
      - "8082:8080"
    depends_on:
      - jaeger-agent

  kafka-streams:
    image: kafka-streams
    environment:
      JAEGER_SERVICE_NAME: kafka-streams
      JAEGER_AGENT_HOST: jaeger-agent
      JAEGER_AGENT_PORT: 5775
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_REPORTER_LOG_SPANS: "true"
    depends_on:
      - kafka
      - jaeger-agent


  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.0-3
    ports:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'

  kafka:
    image: confluentinc/cp-kafka:4.0.0-3
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
    depends_on:
      - zookeeper


  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["/go/bin/agent-linux", "--collector.host-port=jaeger-collector:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    depends_on:
      - jaeger-collector

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["/go/bin/collector-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    depends_on:
      - cassandra-schema

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:3.9

  prometheus:
    image: prom/prometheus:v1.7.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
