apiVersion: v1
kind: Service
metadata:
  name: cluster-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    cluster: example
  ports:
  - port: 19999
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        cluster: example
    spec:
      containers:
      - name: backend
        image: backend:0.1
        env:
        - name: CLUSTER_SERVICE
          value: cluster-service
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        cluster: example
    spec:
      containers:
      - name: frontend
        image: frontend:0.1
        ports:
        - containerPort: 9000
        env:
        - name: CLUSTER_SERVICE
          value: cluster-service
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace