apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        cluster: example
    spec:
      containers:
      - name: backend
        image: backend:0.1
        env:
        - name: CLUSTER_DISCOVERY_SERVICE
          value: cluster-service
