apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        cluster: example
    spec:
      containers:
      - name: frontend
        image: frontend:0.1
        ports:
        - containerPort: 9000
        env:
        - name: CLUSTER_DISCOVERY_SERVICE
          value: cluster-service
